---
# tasks file for docker
- name: Install yum-utils for yum-config-manager
  yum:
    name: yum-utils
    state: latest

- name: Add repository
  shell: |
    yum-config-manager -y --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name:
      - docker-ce-20.10.9
      - docker-ce-cli-20.10.9
      - containerd.io
    allowerasing: true
    nobest: true

- name: Enable the Docker daemon in systemd
  shell: |
    systemctl start docker
    systemctl start containerd
    usermod -aG docker {{ ansible_ssh_user }}
    systemctl enable docker
    systemctl enable containerd

- name: Change docker socket permissions
  shell:
    cmd: chmod 666 /var/run/docker.sock

- name: Download and install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

